version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/back-end/
permissions:
  - object: /home/ubuntu/back-end/
    owner: ubuntu
    group: ubuntu
hooks:
  BeforInstall:
    - location: scripts/karyl2.sh
      runas: root

  AfterInstall:
    - location: scripts/deploy.sh
      runas: root