version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/back-end/
permissions:
  - object: /home/ec2-user/back-end/
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root